[package]
name = "lulo-rust"
version = "0.1.0"
authors = ["Jeff Wise <jeff.scott.wise@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
